(ns pl.tomaszgigiel.quizzes.packs.weird-characters-test
  (:require [clojure.test :as tst])
  (:require [pl.tomaszgigiel.quizzes.test-config :as test-config])
  (:require [pl.tomaszgigiel.quizzes.quiz :refer [qam q a at m]])
  (:require [pl.tomaszgigiel.utils.misc :as misc]))

(tst/use-fixtures :once test-config/once-fixture)
(tst/use-fixtures :each test-config/each-fixture)

(qam
  (q "Discuss the weird characters.")
  (a "() - list")
  (a "[] - vector")
  (a "{} - map")
  (a "# - dispatch character")
  (a "#{} - set")
  (a "#_ - discard")
  (a "#\".\" - regular expression")
  (a "#() - anonymous function")
  (a "#' - var quote")
  (a "## - symbolic values")
  (a "#inst, #uuid, and #js etc. - tagged literals")
  (a "%, %n, %& - anonymous function arguments")
  (a "@ - deref")
  (a "^ (and #^) - metadata")
  (a "' - quote")
  (a "; - comment")
  (a ": - keyword")
  (a ":: - auto-resolved keyword")
  (a "#: and #:: - namespace map syntax")
  (a "/ - namespace separator")
  (a "\\ - character literal")
  (a "$ - inner class reference")
  (a "->, ->>, some->, cond->, as-> etc. - threading macros")
  (a "` - syntax quote")
  (a "~ - unquote")
  (a "~@ - unquote splicing")
  (a "<symbol># - gensym")
  (a "#? - reader conditional")
  (a "#?@ - splicing reader conditional")
  (a "*var-name* - \"earmuffs\"")
  (a ">!!, <!!, >!, and <! - core.async channel macros")
  (a "<symbol>? - predicate suffix")
  (a "<symbol>! - unsafe operations")
  (a "_ - unused argument")
  (a ", - whitespace character")
  (a "#= reader eval")
  (m "https://clojure.org/guides/weird_characters"))
